# combine_control_expr = false
# enum_discrim_align_threshold = 30
# fn_single_line = true
# force_multiline_blocks = true
# format_code_in_doc_comments = true
# format_strings = true
# imports_layout = "Vertical"
# imports_granularity = "Crate"
newline_style = "Unix"
# normalize_doc_attributes = true
# reorder_impl_items = true
# struct_field_align_threshold = 30
use_field_init_shorthand = true
# wrap_comments = true
